import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:trailo/controller/outward/completed_order_list_controller.dart';
import 'package:trailo/model/completed_order/get_completed_order_list_response.dart';
import 'package:trailo/utility/app_routes.dart';
import 'package:trailo/view/outward/completed_order/completed_order_list.dart';

import '../../../utility/app_colors.dart';
import '../../../utility/date_formater.dart';

// CompletedOrderData class definition

class CompletedOrderDetail extends StatefulWidget {
  const CompletedOrderDetail({super.key});

  @override
  State<CompletedOrderDetail> createState() => _CompletedOrderDetailState();
}

class _CompletedOrderDetailState extends State<CompletedOrderDetail> {
  CompletedOrderData? order;
  final controller = Get.put(CompletedOrderListController());
  String? srNo; // Add variable to store serial number

  @override
  void initState() {
    super.initState();
    final arguments = Get.arguments as Map<String, dynamic>;
    setState(() {
      order = arguments['completed_detail'] as CompletedOrderData;
      srNo = arguments['sr_no'] as String; // Retrieve serial number
    });
  }

  String _processType(int status) {
    switch (status) {
      case 0:
        return 'Sales Order';
      case 1:
        return 'Free Issue';
      case 2:
        return 'Sample';
      case 3:
        return 'Transfer';
      default:
        return 'Unknown';
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Completed Order Detail: ${srNo}')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Expanded(
              child: ListView(
                children: [
                  _buildDetailRow('Sr. No.', "${srNo}"),
                  _buildDetailRow(
                    'Date',
                    "${DateFormater.formatDate(order!.orderDate.toString())}",
                  ),
                  _buildDetailRow('Company Name', order!.companyName),
                  _buildDetailRow('Division', order!.divisionName),
                  _buildDetailRow(
                    'Process Type',
                    _processType(int.parse(order!.processType)),
                  ),
                  _buildDetailRow(
                    'Customer Name',
                    order!.customerName.isNotEmpty
                        ? order!.customerName
                        : "N/A",
                  ),
                  _buildDetailRow(
                    'Transport Name',
                    order!.transportName.isNotEmpty
                        ? order!.transportName
                        : "N/A",
                  ),
                  _buildDetailRow(
                    'Issue Name',
                    order != null &&
                            order!.salesTeamEmployeeName != null &&
                            order!.salesTeamEmployeeName!.isNotEmpty
                        ? order!.salesTeamEmployeeName!
                        : 'N/A',
                  ),
                  _buildDetailRow(
                    'Order Date',
                    DateFormater.formatDate(order!.orderDate.toString()),
                  ),
                  _buildDetailRow('Status', order!.statusName),
                  _buildDetailRow(
                    'Invoice Date',
                    "${DateFormater.formatDate(order!.invoiceDateProcess.toString())}",
                  ),
                  _buildDetailRow(
                    'Invoice Number',
                    order!.invoiceNumberProcess,
                  ),
                  _buildDetailRow(
                    'Added By',
                    '${order!.employeeName.toString()} ${order!.salesEmployeeName.toString()}',
                  ),
                  _buildDetailRow(
                    'Invoice Generated By',
                    '${order!.employeeName.toString()}${order!.salesEmployeeName.toString()}',
                  ),
                  _buildDetailRow('LR Number', order!.LrNumber),
                  _buildDetailRow(
                    'LR Date',
                    "${DateFormater.formatDate(order!.LrDate.toString())}",
                  ),
                  _viewButton('Order Copy', () {
                    try {
                      if (order == null || order!.orderCopy == null) {
                        print('Error: order or lrCopy is null');
                        // Optionally show a snackbar or dialog to user
                        // Get.snackbar('Error', 'No document available to view');
                        return;
                      }

                      final filePath = order!.orderCopy
                          .toString()
                          .toLowerCase();
                      final url = '${controller.url.value}${order!.orderCopy}';

                      print('Attempting to open: $url'); // Debug log

                      if (filePath.endsWith('.pdf')) {
                        print('Navigating to PDF viewer');
                        Get.toNamed(AppRoutes.viewpdf, arguments: url);
                      } else if (filePath.endsWith('.jpg') ||
                          filePath.endsWith('.png') ||
                          filePath.endsWith('.jpeg')) {
                        print('Navigating to Image viewer');
                        Get.toNamed(AppRoutes.viewImage, arguments: url);
                      } else {
                        print('Unsupported file type: $filePath');
                        //Get.snackbar('Error', 'Unsupported file format');
                      }
                    } catch (e) {
                      print('Error in viewButton: $e');
                      // Get.snackbar('Error', 'Failed to open document');
                    }
                  }),
                  _viewButton('Invoice Copy', () {
                    try {
                      if (order == null || order!.invoiceCopyNew == null) {
                        print('Error: order or lrCopy is null');
                        // Optionally show a snackbar or dialog to user
                        //  Get.snackbar('Error', 'No document available to view');
                        return;
                      }

                      final filePath = order!.invoiceCopyNew
                          .toString()
                          .toLowerCase();
                      final url =
                          '${controller.url.value}${order!.invoiceCopyNew}';

                      print('Attempting to open: $url'); // Debug log

                      if (filePath.endsWith('.pdf')) {
                        print('Navigating to PDF viewer');
                        Get.toNamed(AppRoutes.viewpdf, arguments: url);
                      } else if (filePath.endsWith('.jpg') ||
                          filePath.endsWith('.png') ||
                          filePath.endsWith('.jpeg')) {
                        print('Navigating to Image viewer');
                        Get.toNamed(AppRoutes.viewImage, arguments: url);
                      } else {
                        print('Unsupported file type: $filePath');
                        //Get.snackbar('Error', 'Unsupported file format');
                      }
                    } catch (e) {
                      print('Error in viewButton: $e');
                      // Get.snackbar('Error', 'Failed to open document');
                    }
                  }),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildDetailRow(String label, String value) {
    return Card(
      margin: const EdgeInsets.symmetric(vertical: 4),
      child: Padding(
        padding: const EdgeInsets.all(12.0),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(
              width: 150,
              child: Text(
                label,
                style: const TextStyle(
                  fontWeight: FontWeight.bold,
                  color: Colors.black,
                  fontSize: 13,
                ),
              ),
            ),
            const Text(': ', style: TextStyle(fontSize: 15)),
            Expanded(
              child: Text(
                value,
                style: const TextStyle(fontSize: 15),
                maxLines: 3, // Allow up to 3 lines for long text
                overflow: TextOverflow
                    .ellipsis, // Add ellipsis if text exceeds maxLines
                softWrap: true, // Enable text wrapping
              ),
            ),
          ],
        ),
      ),
    );
  }

  Card _viewButton(String label, VoidCallback press) {
    return Card(
      margin: const EdgeInsets.symmetric(vertical: 4),
      child: Padding(
        padding: const EdgeInsets.all(12.0),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(
              width: 150,
              child: Text(
                label,
                style: const TextStyle(
                  fontWeight: FontWeight.bold,
                  color: Colors.black,
                  fontSize: 13,
                ),
              ),
            ),
            Expanded(
              child: Row(
                children: [
                  const Text(": ", style: TextStyle(fontSize: 15)),
                  GestureDetector(
                    onTap: press,
                    child: AnimatedContainer(
                      duration: const Duration(milliseconds: 200),
                      transform: Matrix4.identity()..scale(1.0),
                      child: Material(
                        color: Colors.transparent,
                        child: InkWell(
                          borderRadius: BorderRadius.circular(8),
                          onTap: press,
                          splashColor: Colors.white.withOpacity(0.3),
                          child: Container(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 12,
                              vertical: 8,
                            ),
                            decoration: BoxDecoration(
                              color: AppColors.primary,
                              borderRadius: BorderRadius.circular(8),
                              boxShadow: [
                                BoxShadow(
                                  color: Colors.black.withOpacity(0.1),
                                  blurRadius: 4,
                                  offset: const Offset(0, 2),
                                ),
                              ],
                            ),
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                Text(
                                  "View",
                                  style: GoogleFonts.poppins(
                                    color: Colors.white,
                                    fontWeight: FontWeight.w500,
                                    fontSize: 14,
                                  ),
                                  semanticsLabel: "View Button",
                                ),
                                const SizedBox(width: 6),
                                const Icon(
                                  Icons.remove_red_eye,
                                  color: Colors.white,
                                  size: 18,
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
